import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-off-market',
  templateUrl: './off-market.component.html',
  styleUrl: './off-market.component.css'
})
export class OffMarketComponent {
  listing = [
    { active: '2', pending: '0', rejected: '0', expired: '0', deleted: '0', Downgraded: '0', inactive: '0', publish: '4', unPublish:'2' }
  ]
  
  listingCard = [
    {
      image: '../../assets/img/carousel-img-1.png',
      id: '1234567',
      status: 'Active',
      title: 'New Apartment Nice View',
      address: 'Quincy St, Brooklyn, NY, USA',
      bed: '02',
      bath: '03',
      sqFt: '1200',
      price: '25000',
      impression: '1000',
      view: '55',
      call: '3',
      email: '12',
      created: '16/05/2024',
      createdTime: '10:20AM',
      expire: '24/05/2024',
      expireTime: '10:20AM',
      edit: '',
      publish: '',
    },
    {
      image: '../../assets/img/carousel-img-1.png',
      id: '1234567',
      status: 'Active',
      title: 'New Apartment Nice View',
      address: 'Quincy St, Brooklyn, NY, USA',
      bed: '02',
      bath: '03',
      sqFt: '1200',
      price: '25000',
      impression: '1000',
      view: '55',
      call: '3',
      email: '12',
      created: '16/05/2024',
      createdTime: '10:20AM',
      expire: '24/05/2024',
      expireTime: '10:20AM',
      edit: '',
      publish: '',
    },
    {
      image: '../../assets/img/carousel-img-1.png',
      id: '1234567',
      status: 'Active',
      title: 'New Apartment Nice View',
      address: 'Quincy St, Brooklyn, NY, USA',
      bed: '02',
      bath: '03',
      sqFt: '1200',
      price: '25000',
      impression: '1000',
      view: '55',
      call: '3',
      email: '12',
      created: '16/05/2024',
      createdTime: '10:20AM',
      expire: '24/05/2024',
      expireTime: '10:20AM',
      edit: '',
      publish: '',
    },
    {
      image: '../../assets/img/carousel-img-1.png',
      id: '1234567',
      status: 'Active',
      title: 'New Apartment Nice View',
      address: 'Quincy St, Brooklyn, NY, USA',
      bed: '02',
      bath: '03',
      sqFt: '1200',
      price: '25000',
      impression: '1000',
      view: '55',
      call: '3',
      email: '12',
      created: '16/05/2024',
      createdTime: '10:20AM',
      expire: '24/05/2024',
      expireTime: '10:20AM',
      edit: '',
      publish: '',
    },
    {
      image: '../../assets/img/carousel-img-1.png',
      id: '1234567',
      status: 'Active',
      title: 'New Apartment Nice View',
      address: 'Quincy St, Brooklyn, NY, USA',
      bed: '02',
      bath: '03',
      sqFt: '1200',
      price: '25000',
      impression: '1000',
      view: '55',
      call: '3',
      email: '12',
      created: '16/05/2024',
      createdTime: '10:20AM',
      expire: '24/05/2024',
      expireTime: '10:20AM',
      edit: '',
      publish: '',
    },
    {
      image: '../../assets/img/carousel-img-1.png',
      id: '1234567',
      title: 'New Apartment Nice View',
      address: 'Quincy St, Brooklyn, NY, USA',
      bed: '02',
      bath: '03',
      sqFt: '1200',
      price: '25000',
      impression: '1000',
      view: '55',
      call: '3',
      email: '12',
      created: '16/05/2024',
      createdTime: '10:20AM',
      expire: '24/05/2024',
      expireTime: '10:20AM',
      edit: '',
      publish: '',
    },
  ]

}
